spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY;
    username: sa
    password:
  jpa:
    properties:
      format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  docker:
    compose:
      enabled: false
      file: ./docker-compose.yml
  mvc:
     problemdetails:
       enabled: true
#LOGGING CONFIGURATION
logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder=TRACE:
        sql: info